language: c

sudo: false

matrix:
  include:
    - env: LUA="lua 5.1"
      os: linux
    - env: LUA="lua 5.2"
      os: linux
    - env: LUA="lua 5.3"
      os: linux
    - env: LUA="luajit 2.0"
      os: linux
    - env: LUA="luajit 2.1"
      os: linux

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - pip2 install --user cpp-coveralls
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - luarocks show lluv > /dev/null 2>&1 || bash .travis/setup_uv.sh

install:
  - luarocks show vararg > /dev/null 2>&1 || luarocks install vararg
  - luarocks show lluv   > /dev/null 2>&1 || luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks make rockspecs/lluv-memcached-scm-0.rockspec UV_DIR=$TRAVIS_BUILD_DIR/libuv

before_script:
  - luarocks show lua_cliargs      > /dev/null 2>&1 || luarocks install lua_cliargs 2.5
  - luarocks show stacktraceplus   > /dev/null 2>&1 || luarocks install stacktraceplus
  - luarocks show lua-cjson        > /dev/null 2>&1 || luarocks install lua-cjson
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls
  - luarocks show lluv-busted      > /dev/null 2>&1 || luarocks install lluv-busted --server=http://luarocks.org/dev

script: 
  - cd test
  - busted_bootstrap --verbose --coverage test.busted
  - lua ../examples/perfomance.lua

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
