language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
      os: linux
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
      os: linux
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
      os: linux
    # - compiler: ": LuaJIT20"
    #   env: LUA="luajit 2.0"
    #   os: linux
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"
      os: linux
    # - compiler: ": Lua51-osx"
    #   env: LUA="lua 5.1"
    #   os: osx

services:
  - memcached

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - gcc --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - luarocks show lluv > /dev/null 2>&1 || bash .travis/setup_uv.sh

install:
  - luarocks show vararg > /dev/null 2>&1 || luarocks install vararg
  - luarocks show lluv   > /dev/null 2>&1 || luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks make rockspecs/lluv-memcached-scm-0.rockspec UV_DIR=$TRAVIS_BUILD_DIR/libuv

before_script:
  - luarocks show lua-cjson        > /dev/null 2>&1 || luarocks install lua-cjson
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls

script: 
  - cd test
  - lua -lluacov self_test.lua
  - lua ../examples/perfomance.lua

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
